services:
    app:
        container_name: airq-server
        build:
            context: .
            dockerfile: Dockerfile
        image: airq-server:latest
        ports:
            - "5500:5500"
        env_file:
            - .env

        command: ["node", "-r", "tsconfig-paths/register", "dist/server.js"]
