services:
  app:
    container_name: airq-server
    build:
      context: .
      dockerfile: Dockerfile
    image: airq-server:latest
    ports:
      - "5500:5500"
    env_file:
      - .env
    volumes:
      - .:/app
    command: ["node", "-r", "tsconfig-paths/register", "server.js"]
