/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AlertsSetting {
  aqi_index: Generated<boolean>;
  district_id: string;
  id: Generated<number>;
  pm_25: Generated<boolean>;
  temperature: Generated<boolean>;
  user_id: number;
  weather: Generated<boolean>;
  wind_speed: Generated<boolean>;
}

export interface CronjobMonitor {
  id: Generated<number>;
  raster_data_status: number;
  station_data_log: string;
  station_data_status: number;
  timestamp: Timestamp;
  wind_data_log: string;
  wind_data_status: number;
}

export interface GeographyColumns {
  coord_dimension: number | null;
  f_geography_column: string | null;
  f_table_catalog: string | null;
  f_table_name: string | null;
  f_table_schema: string | null;
  srid: number | null;
  type: string | null;
}

export interface GeometryColumns {
  coord_dimension: number | null;
  f_geometry_column: string | null;
  f_table_catalog: string | null;
  f_table_name: string | null;
  f_table_schema: string | null;
  srid: number | null;
  type: string | null;
}

export interface Mail {
  html: string;
  id: number;
  subject: string;
}

export interface MDistricts {
  created_at: Generated<Timestamp | null>;
  deleted: Generated<number | null>;
  district_id: string;
  eng_district: string;
  eng_type: string;
  province_id: string;
  updated_at: Generated<Timestamp | null>;
  vn_district: string;
  vn_province: string;
  vn_type: string;
}

export interface MRecommendation {
  color: string;
  en_recommendation: string;
  en_status: string;
  id: Generated<number>;
  max_threshold: number;
  min_threshold: number;
  vn_recommendation: string | null;
  vn_status: string | null;
}

export interface RasterColumns {
  blocksize_x: number | null;
  blocksize_y: number | null;
  extent: string | null;
  nodata_values: number[] | null;
  num_bands: number | null;
  out_db: boolean[] | null;
  pixel_types: string[] | null;
  r_raster_column: string | null;
  r_table_catalog: string | null;
  r_table_name: string | null;
  r_table_schema: string | null;
  regular_blocking: boolean | null;
  same_alignment: boolean | null;
  scale_x: number | null;
  scale_y: number | null;
  spatial_index: boolean | null;
  srid: number | null;
}

export interface RasterOverviews {
  o_raster_column: string | null;
  o_table_catalog: string | null;
  o_table_name: string | null;
  o_table_schema: string | null;
  overview_factor: number | null;
  r_raster_column: string | null;
  r_table_catalog: string | null;
  r_table_name: string | null;
  r_table_schema: string | null;
}

export interface SpatialRefSys {
  auth_name: string | null;
  auth_srid: number | null;
  proj4text: string | null;
  srid: number;
  srtext: string | null;
}

export interface Stations {
  address: string | null;
  aqi_index: number;
  color: string;
  geom: string | null;
  lat: number;
  lng: number;
  pm25: number | null;
  station_id: string;
  station_name: string | null;
  status: string;
  timestamp: Timestamp | null;
}

export interface Statistics {
  aqi_index: number;
  created_at: Generated<Timestamp | null>;
  deleted: Generated<number | null>;
  district_id: string | null;
  id: Generated<number>;
  pm_25: number;
  time: Timestamp | null;
  updated_at: Generated<Timestamp | null>;
}

export interface Users {
  created_at: Generated<Timestamp | null>;
  deleted: Generated<number | null>;
  email: string;
  password: string;
  phone_number: string;
  role: Generated<number>;
  updated_at: Generated<Timestamp | null>;
  user_id: Generated<number>;
  username: string;
}

export interface UsersNotification {
  aqi_index: number | null;
  archived: Generated<number | null>;
  id: Generated<number>;
  location_id: string | null;
  recommendation_id: number | null;
  timestamp: Generated<Timestamp | null>;
  user_id: number | null;
}

export interface UsersSetting {
  created_at: Generated<Timestamp | null>;
  deleted: Generated<number | null>;
  id: Generated<number>;
  profile_url: string | null;
  receive_notifications: Generated<number | null>;
  updated_at: Generated<Timestamp | null>;
  user_id: number | null;
  user_location: string | null;
}

export interface WindData {
  id: Generated<number>;
  timestamp: Timestamp;
  ugrid_data: number[];
  vgrid_data: number[];
}

export interface DB {
  alerts_setting: AlertsSetting;
  cronjob_monitor: CronjobMonitor;
  geography_columns: GeographyColumns;
  geometry_columns: GeometryColumns;
  m_districts: MDistricts;
  m_recommendation: MRecommendation;
  mail: Mail;
  raster_columns: RasterColumns;
  raster_overviews: RasterOverviews;
  spatial_ref_sys: SpatialRefSys;
  stations: Stations;
  statistics: Statistics;
  users: Users;
  users_notification: UsersNotification;
  users_setting: UsersSetting;
  wind_data: WindData;
}
