/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AQISupa {
  elevation: number | null;
  fid: Generated<number>;
  ingestion: Timestamp | null;
  location: string | null;
  the_geom: string | null;
}

export interface GeographyColumns {
  coord_dimension: number | null;
  f_geography_column: string | null;
  f_table_catalog: string | null;
  f_table_name: string | null;
  f_table_schema: string | null;
  srid: number | null;
  type: string | null;
}

export interface GeometryColumns {
  coord_dimension: number | null;
  f_geometry_column: string | null;
  f_table_catalog: string | null;
  f_table_name: string | null;
  f_table_schema: string | null;
  srid: number | null;
  type: string | null;
}

export interface MDistricts {
  created_at: Generated<Timestamp | null>;
  deleted: Generated<number | null>;
  district_id: string;
  eng_district: string;
  eng_type: string;
  province_id: string;
  updated_at: Generated<Timestamp | null>;
  vn_district: string;
  vn_province: string;
  vn_type: string;
}

export interface MRecommendation {
  color: string;
  id: Generated<number>;
  max_threshold: number;
  min_threshold: number;
  recommendation: string;
  status: string;
}

export interface PointsData {
  geom: string | null;
  id: Generated<number>;
  name: string | null;
  point_value: number;
}

export interface SpatialRefSys {
  auth_name: string | null;
  auth_srid: number | null;
  proj4text: string | null;
  srid: number;
  srtext: string | null;
}

export interface Stations {
  aqi_index: number | null;
  created_at: Generated<Timestamp | null>;
  deleted: Generated<number | null>;
  lat: number | null;
  lng: number | null;
  station_id: string;
  station_name: string;
  status: string;
  timestamp: Timestamp | null;
  updated_at: Generated<Timestamp | null>;
}

export interface StationsPointMap {
  aqi_index: number;
  color: string;
  geom: string | null;
  lat: number;
  lng: number;
  station_id: string;
  status: string;
  timestamp: Timestamp | null;
}

export interface Statistics {
  aqi_index: number;
  created_at: Generated<Timestamp | null>;
  deleted: Generated<number | null>;
  district_id: string | null;
  id: Generated<number>;
  pm_25: number;
  time: Timestamp | null;
  updated_at: Generated<Timestamp | null>;
}

export interface Users {
  created_at: Generated<Timestamp | null>;
  deleted: Generated<number | null>;
  email: string;
  password: string;
  phone_number: string;
  role: Generated<number>;
  updated_at: Generated<Timestamp | null>;
  user_id: Generated<number>;
  username: string;
}

export interface UsersSession {
  access_token: string;
  created_at: Generated<Timestamp | null>;
  deleted: number | null;
  id: Generated<number>;
  refresh_token: string | null;
  session_id: string;
  updated_at: Generated<Timestamp | null>;
  user_id: number;
}

export interface UsersSetting {
  created_at: Generated<Timestamp | null>;
  deleted: Generated<number | null>;
  email_notification: Generated<boolean | null>;
  id: number;
  profile_url: string | null;
  sms_notification: Generated<boolean | null>;
  updated_at: Generated<Timestamp | null>;
  user_id: number | null;
  user_location: string | null;
}

export interface DB {
  AQI_Supa: AQISupa;
  geography_columns: GeographyColumns;
  geometry_columns: GeometryColumns;
  m_districts: MDistricts;
  m_recommendation: MRecommendation;
  points_data: PointsData;
  spatial_ref_sys: SpatialRefSys;
  stations: Stations;
  stations_point_map: StationsPointMap;
  statistics: Statistics;
  users: Users;
  users_session: UsersSession;
  users_setting: UsersSetting;
}
