name: 'Server AWS CodeBuild CI'
on:
  push:
    branches:
      - 'release'

jobs:
  build:
    runs-on: codebuild-airq-${{github.run_id}}-${{github.run_attempt}}
    steps:
      - name: cd to server dir
        run: cd air-quality/server
      - name: Install npm packages
        run: npm install
      - name: Build
        run: npm run build
      