name: 'Server AWS CodeBuild CI'
on:
  push:
    branches:
      - 'release'

jobs:
  build:
    runs-on:
      - codebuild-airq-${{github.run_id}}-${{github.run_attempt}}
      - buildspec-override:true
    steps:
      - name: Finish
        run: echo "Hello World"
