name: 'Server AWS CodeBuild CI'
on:
  push:
    branches:
      - 'release'

jobs:
  build:
    runs-on: codebuild-airq-${{github.run_id}}-${{github.run_attempt}} # Ensure you're using GitHub-hosted runners for GitHub Actions

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'ap-southeast-1'

      - name: Install dependencies
        run: |
          npm install -g node-gyp

      - name: Download secrets from AWS Secrets Manager
        run: |
          cd server
          aws secretsmanager list-secrets --query 'SecretList[*].Name' --output text | tr '\t' '\n' | while read secret; do
            aws secretsmanager get-secret-value --secret-id "$secret" --query SecretString --output text | jq -r 'to_entries | .[] | "\(.key)=\(.value)"' >> .env
          done

      - name: Build application
        run: |
          cd server
          npm run build

      - name: Run Docker and Upload to S3
        run: |
          cd server
          aws s3 cp dist s3://uet-airq/build/ --recursive
        # docker build -t airq-server .
        # docker save airq-server:latest | gzip > airq-server.tar.gz

      # Uncomment the below section if needed to sync the dist directory
      # - name: Create artifact
      #   run: |
      #     aws s3 sync server/dist s3://uet-airq/dist --delete
